#' Create a skeleton for a new source package with Rust support
#'
#' Create a skeleton for a new source package with Rust support.
#'
#' There is a folder name \code{rustlib} in the created package \code{src} path. This folder is a rust library which will be compiled and linked by R. Just write Rust code in \code{./src/rustlib/src/} .
#'
#' \code{./src/rustlib/src/export.rs}, \code{./src/REXPORT.c} and \code{./R/REXPORT.R} are generated by \code{rustrize()}, and they should not be edited by hand. Before building the package, run \code{rustrize()} to generate these three files.
#'
#' @param name A character string: the package name and directory name for your package.
#' @param path A path to put the package directory in.
#' @param force See \link[utils]{package.skeleton}
#' @param code_files See \link[utils]{package.skeleton}
#' @param rust_files A character vector with the paths to Rust source files to add to the package.
#' @param author Author of the package.
#' @param maintainer Maintainer of the package.
#' @param email Email of the package maintainer.
#' @param license License of the package.
#' @references
#' Read the \emph{Writing R Extensions} manual for more details.
#' @seealso https://book.rustr.org/create-a-rust-r-package.html
#' @examples
#' \dontrun{
#'
#' rustr_init("test-pkg")
#' }
#' @export
rustr_init <- function(name,
                       path = ".",
                       force = FALSE,
                       code_files = character(),
                       rust_files = character(),
                       author = "Your Name",
                       maintainer = if (missing(author))
                           "Your Name"
                       else
                           author,
                       email = "your@email.com",
                       license = "MIT") {
    if (!is.character(rust_files))
        stop("'rust_files' must be a character vector")

    hienv = new.env(parent = emptyenv())
    hienv$hi = function() {
        "hi"
    }
    tryCatch(
        package.skeleton(
            name = name,
            environment = hienv,
            path = path,
            force = force,
            code_files = code_files
        ),
        error = function(e) {
            stop(sprintf(
                "error while calling `package.skeleton` : %s",
                conditionMessage(e)
            ))
        }
    )

    root <- file.path(path, name)

    DESCRIPTION <- file.path(root, "DESCRIPTION")
    if (file.exists(DESCRIPTION)) {
        x <- read.dcf(DESCRIPTION)
        x[, "Author"] <- author
        x[, "Maintainer"] <- sprintf("%s <%s>", maintainer, email)
        x[, "License"] <- license
        x = cbind(x, SystemRequirements = "cargo, rustc")
        write.dcf(x, file = DESCRIPTION)
    }

    NAMESPACE <- file.path(root, "NAMESPACE")
    lines <- readLines(NAMESPACE)
    ns <- file(NAMESPACE, open = "w")
    if (!grepl("useDynLib", lines)) {
        lines <- c(sprintf("useDynLib(%s)", name), lines)
        writeLines(lines, con = ns)
        message("added useDynLib to NAMESPACE")
    }
    close(ns)


    package_help_page <-
        file.path(root, "man", sprintf("%s-package.Rd", name))
    if (file.exists(package_help_page)) {
        lines <- readLines(package_help_page)
        lines <-
            gsub("What license is it under?", license, lines, fixed = TRUE)
        lines <-
            gsub(
                "Who to complain to <yourfault@somewhere.net>",
                sprintf("%s <%s>", maintainer, email),
                lines,
                fixed = TRUE
            )
        lines <- gsub("Who wrote it", author, lines, fixed = TRUE)
        writeLines(lines, package_help_page)
    }

    src <- file.path(root, "src")
    if (!file.exists(src)) {
        dir.create(src)
    }
    rustlib_src = file.path(root, "src", "rustlib")
    if (!file.exists(rustlib_src)) {
        dir.create(rustlib_src)
    }
    rust_src_src = file.path(rustlib_src, "src")
    if (!file.exists(rust_src_src)) {
        dir.create(rust_src_src)
    }
    skeleton <- system.file("init", package = "rustinr")

    if (length(rust_files) > 0L) {
        for (file in rust_files) {
            file.copy(file, src)
            message(" >> copied ", file, " to src directory")
        }
    }

    file.copy(file.path(skeleton, "Makevars.win"),
              file.path(src, "Makevars.win"))
    if(Sys.info()["sysname"] == "FreeBSD"){
        file.copy(file.path(skeleton, "Makevars.bsd"),
                  file.path(src, "Makevars"))
    } else{
        file.copy(file.path(skeleton, "Makevars"),
                  file.path(src, "Makevars"))
    }


    file.copy(file.path(skeleton, "Cargo.toml"),
              file.path(rustlib_src, "Cargo.toml"))

    file.copy(file.path(skeleton, "lib.rs"),
              file.path(rust_src_src, "lib.rs"))

    manu <- file.path(root, "man")
    suppressWarnings(file.remove(file.path(manu, "hi.Rd")))
    suppressWarnings(file.remove(file.path(manu, paste0(name,"-package.Rd"))))
    rustrize(root)
    message("\n")
    message("It is recommended to change the rustr version in ./src/rustlib/Cargo.toml from \"*\" to a specific version number to get reproducibility.")
    invisible(NULL)
}
